import {StyleSheet} from 'react-native';
import Colors from './colors';

export const PRIMARY_FONT_REGULAR = 'NeueHaasDisplayRoman'; // 400
export const PRIMARY_FONT_MEDIUM = 'NeueHaasDisplayMedium'; // 500
export const PRIMARY_FONT_BOLD = 'NeueHaasDisplayBold'; // 600

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  primaryBtn: {
    backgroundColor: Colors.primaryBtnBackground,
    width: '100%',
    minHeight: 52,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtnText: {
    color: Colors.primaryBtnText,
    textAlign: 'center',
    fontSize: 18,
    fontFamily: PRIMARY_FONT_MEDIUM,
    fontWeight: '600',
    letterSpacing: 0.36,
  },
  textLinkBtn: {
    backgroundColor: 'transparent',
    width: 'auto',
    minHeight: 'auto',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textLinkBtnText: {
    color: Colors.interactive,
    textAlign: 'center',
    fontSize: 15,
    fontFamily: PRIMARY_FONT_REGULAR,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: 0.6,
    textDecorationLine: 'underline',
  },
  font32: {
    color: Colors.primary,
    fontSize: 32,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 38,
    fontWeight: '500',
    letterSpacing: 0.64,
  },
  font16: {
    color: Colors.primary,
    fontSize: 16,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 20,
    letterSpacing: 0.64,
  },
  font15Gray: {
    color: Colors.secondary,
    fontSize: 15,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 20,
    fontWeight: '400',
    letterSpacing: 0.64,
  },
  backBtn: {
    position: 'absolute',
    top: 20,
    left: 15,
    padding: 5,
    zIndex: 1000,
  },
  xpBtn: {
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 54,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.golden,
    backgroundColor: Colors.blurredGray,
  },
  xpBtnText: {
    color: Colors.golden,
    fontSize: 14,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 16.8,
    fontWeight: '400',
    letterSpacing: 0.28,
  },
  xpSparkle: {
    width: 18,
    height: 18,
    position: 'absolute',
    top: 0,
    right: -7,
    overflow: 'visible',
  },
  screenTitle: {
    color: Colors.primary,
    fontSize: 38,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 46,
    fontWeight: '500',
    letterSpacing: 0.84,
  },
  screenDescription: {
    marginTop: 8,
    color: Colors.secondary,
    fontSize: 18,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 21.6,
    fontWeight: '400',
    letterSpacing: 0.72,
  },
  inputContainer: {
    height: 52,
    paddingHorizontal: 20,
    width: '100%',
    backgroundColor: Colors.blurredGray,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    color: Colors.primary,
    fontSize: 16,
    fontFamily: PRIMARY_FONT_REGULAR,
    lineHeight: 19.2,
    fontWeight: '600',
    letterSpacing: 0.32,
  },
  inputIcon: {},
  nextBtn: {
    width: 200,
  },
});

export default styles;
